---
AssignmentInConditionalCheck:
CaseMissingElseCheck:
ClassLineCountCheck:
  line_count: 130
ClassNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ClassVariableCheck:
CyclomaticComplexityBlockCheck:
  complexity: 2
CyclomaticComplexityMethodCheck:
  complexity: 4
EmptyRescueBodyCheck:
ForLoopCheck:
MethodLineCountCheck:
  line_count: 6
MethodNameCheck:
  pattern: !ruby/regexp /^[\||\^|\&|\!]$|^[_a-z<>=\[|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/
ModuleLineCountCheck:
  line_count: 130
ModuleNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ParameterNumberCheck:
  parameter_count: 4
